### ISSUE TITLE
plugin选择js的话，build的时候会报错

### ISSUE THREAD

**Issue by SyanH** [moonrailgun/mini-star#12]
如题，需要在tsconfig.json中加上allowJs: true，才可以
另外是否考虑加上类似hook的东西，这样就可以在基座项目中预留位置，在插件中hook进去，前端不太懂，只是个建议，看好这个项目，貌似解决了前后端分离这种后台的插件化问题。感谢！

**Comment by moonrailgun** [comment]
Hi @SyanH , 感谢您对本项目的支持。

> 如题，需要在tsconfig.json中加上allowJs: true，才可以

Fix in `0.0.24`

> 另外是否考虑加上类似hook的东西，这样就可以在基座项目中预留位置，在插件中hook进去

这种 hook 应当是由基座项目自己提供的。并不属于`MiniStar`的职责范围
类似的用法可以参考[`TRPG Engine`](https://github.com/TRPGEngine/Client)的用法

创建hook:
https://github.com/TRPGEngine/Client/blob/master/src/web/reg/regMessageCard.ts#L3

共享模块:
https://github.com/TRPGEngine/Client/blob/master/src/web/plugin-loader.ts#L47-L50

在插件中注入插件的代码:
https://github.com/TRPGEngine/Client/blob/master/src/plugins/trpg/src/reg.tsx#L67

在基座项目中使用:
https://github.com/TRPGEngine/Client/blob/master/src/web/components/messageTypes/card/index.tsx#L29

**Comment by SyanH** [comment]
好的，感谢！
