### ISSUE TITLE
full的示例中点按钮加载test组件，tets组件加载alert依赖时报错

### ISSUE THREAD

**Issue by zjfjiayou** [moonrailgun/mini-star#59]
堆栈错误如下
TypeError: Cannot read properties of undefined (reading 'url')
    at helper.js:135:1
    at step (helper.js:33:1)
    at Object.next (helper.js:14:1)
    at helper.js:8:1
    at new Promise (<anonymous>)
    at __webpack_modules__../node_modules/mini-star/lib/runtime/helper.js.__awaiter (helper.js:4:1)
    at loadDependency (helper.js:87:1)
    at helper.js:172:1
    at Array.map (<anonymous>)
    at requirePlugin (helper.js:171:1)

TypeError: Cannot read properties of undefined (reading 'url') at http://127.0.0.1:8080/bundle.js?76f547da577a4425b9ab:374:44

**Comment by moonrailgun** [comment]
在 2.0.0 已修复这个问题。因为之前是使用 `2.0.0-alpha.1` 导致 lerna 在安装的时候可能会安装到线上的版本(1.3.1)

**Comment by zjfjiayou** [comment]
好的，可能是我本地nrm改了地址的原因，改回来安装一下就好了。
另外还要个问题，例子中alert组件使用sweetalert2，但是没有注册sweetalert2的包，我在项目里添加了 `regDependency('sweetalert2', () => import('sweetalert2'));` 就好了

**Comment by moonrailgun** [comment]
@zjfjiayou  关于ministar 的实践可以看下这个项目: https://github.com/msgbyte/tailchat

另外 sweetalert2 这个库是由插件自己打包的。不应该在基座项目中注册。

https://github.com/moonrailgun/mini-star/blob/83b2fd27df5026010f74402a722074525265bee4/example/full/plugins/alert/package.json#L1-L8

**Comment by zjfjiayou** [comment]
我有看到@plugins/alert组件依赖sweetalert2，我用的是 build:plugins 命令打包的，@plugins/alert组件打包出来的源码没有包含sweetalert2，不知你说的插件自动打包sweetalert2是需要单独写命令吗？
下面是 build:plugins打包出来的源码
`definePlugin('@plugins/alert', ['exports', 'sweetalert2'], (function (exports, Swal) { 'use strict';

  function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

  var Swal__default = /*#__PURE__*/_interopDefaultLegacy(Swal);

  function alert(text) {
    Swal__default["default"].fire(text);
  }

  exports.alert = alert;

  Object.defineProperty(exports, '__esModule', { value: true });

}));
//# sourceMappingURL=index.js.map`

**Comment by moonrailgun** [comment]
这个问题应该是因为插件中的依赖没有被正确安装导致的，lerna做多包管理确实有一定的复杂度（我已经忘了lerna怎么玩的了）。现在我已经修改为pnpm作为多包管理和依赖管理工具了。正确的行为应该是这样的：

![20221021151441_rec_](https://user-images.githubusercontent.com/6964737/197135796-4e0a221e-6a81-49a7-9413-f07543a2daca.gif)

pnpm快速上手:
```bash
npm install -g pnpm # 全局安装pnpm
pnpm install # 在项目根目录中执行安装命令，会把所有的子包都一起进行依赖安装
```
