### ISSUE TITLE
vue2 rollup打包失败 

### ISSUE THREAD

**Issue by wxdx** [moonrailgun/mini-star#69]
.ministarrc.js
[![pSxNLIP.png](https://s1.ax1x.com/2023/02/23/pSxNLIP.png)](https://imgse.com/i/pSxNLIP)
Compont.vue
[![pSxNqat.png](https://s1.ax1x.com/2023/02/23/pSxNqat.png)](https://imgse.com/i/pSxNqat)
编译结果
[![pSxNXPf.png](https://s1.ax1x.com/2023/02/23/pSxNXPf.png)](https://imgse.com/i/pSxNXPf)

去掉 
<script>
console.log(1122)
</script>
就可以打包成功

插件版本

 "rollup-plugin-vue": "^5.0.1",
  "rollup-plugin-commonjs": "^10.1.0",
  "rollup-plugin-node-resolve": "^5.2.0",

**Comment by moonrailgun** [comment]
我不是很了解vue, 我不确定 `rollup-plugin-vue`插件 能否在 vue2 上面是否能够生效。(因为这是为vue3制作的)

 但是我看这个报错是因为script内部没有export任意代码，或许你需要 `export default {}` ?

![image](https://user-images.githubusercontent.com/6964737/220886431-83cbeb55-1131-4bcc-b5dc-0041c2d331bb.png)

**Comment by wxdx** [comment]
感谢  明早我试一下
