### ISSUE TITLE
我有个类似的框架，感兴趣可以瞧一下

### ISSUE THREAD

**Issue by happysmile12321** [moonrailgun/mini-star#72]
https://github.com/reduce4/reduce-plugin-system
我这个主要是可以适配pc,移动，vr平台，有兴趣可以一期搞啊

**Comment by moonrailgun** [comment]
我大概看了一下，你这套东西有点类似jquery时代直接的直接下载html然后放到网页上，只不过用更加现代的方式实现了一遍。

似乎和我做的不是同一套东西。

另外建议不要在其他人仓库中开issue进行宣传，这是一种非常不礼貌的行为。因为跟项目无关也不是问题，我这边先关闭了。

**Comment by happysmile12321** [comment]
非常抱歉，不过我的框架并不像你说的那样。主要思想是通过dsl描述业务组件，然后用各个平台的渲染技术去充当视图组件，然后使用wasm提供插件的数据获取，数据流编排，使用各自的渲染引擎充当数据流管理器。
基于我的思想，A插件可以调用B插件提供的特色服务，方便编排出更个性化的插件。

**Comment by moonrailgun** [comment]
我明白你的意思，但是其本质还是jquery加载html这一套。
无非是中间介质是你自己实现的DSL而不是html文本。

jquery: 请求远程数据 -> 获取html -> 不同浏览器内核生成对应的AST -> 渲染
你的: 请求远程数据 -> 获取DSL -> 根据不同的平台生成对应的AST -> 渲染

抛开现象看本质就是一类东西。而我做的其实是类似requirejs, commonjs 这样的东西，因此我认为是两种东西
不知道我理解的是否有偏差？

**Comment by happysmile12321** [comment]
看了其他人基于你的项目之上实现了自己的基于js的插件系统，也看了你的代码实现。
稍微有些出入。
以下是理解偏差的地方：
1.我框架的部分想将插件的导入啊，依赖复用啊，版本啊，交给各自的平台去实现。例如：js就交给类似于你的框架那一套处理插件，dart和c#交给类似的框架去处理。
2.使用wasm来抽象插件市场有的一部分逻辑，例如插件下载，更新，卸载，等等，然后在flutter,unity上复用这部分逻辑。
因为看到了你的项目，感觉可能会对我的开发产生帮助，有感而发，所以来此评论。

**Comment by moonrailgun** [comment]
了解，如果能帮助到你的话非常高兴。

需要注意的是，如果你的设计是支援多平台(比如一套代码可以同时应用到flutter,unity,js上)那么一定会出现跨平台兼容性的问题。就类似很多跨平台的框架(ios/android跨平台，各类小程序跨平台)，都会出现功能必定为两者交集的问题，而非交集的特性要么都处理要么写两套。
