### ISSUE TITLE
js.map打包问题 || js.map packaging problem when buildingPlugin

### ISSUE THREAD

**Issue by tciooc** [moonrailgun/mini-star#80]
你好，如何在buildPlugin时避免生成*.js.map文件

---
Hello, how to avoid generating *.js.map files

**Comment by moonrailgun** [comment]
v2.1.6 增加了 `sourceMap` 配置。更新到最新版本并设置为 `false` 即可

**Comment by moonrailgun** [comment]
https://ministar.moonrailgun.com/docs/tutorial/guide/ministarrc#sourcemap
